"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { isAdminEmail } from "@/lib/admin";
import { blogPosts } from "@/lib/blog-posts";
import { safeBlocks, slugify, staticBlocks } from "@/lib/blog-cms";
import { sanitizeRichNode } from "@/lib/rich-content";

async function requireAdmin(){ const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user) throw new Error("Unauthorized"); const {data:p}=await s.from("users").select("role").eq("id",user.id).single(); if(p?.role!=="admin"&&!isAdminEmail(user.email)) throw new Error("Unauthorized"); return user; }
function text(f:FormData,k:string,n=500){ return String(f.get(k)||"").trim().slice(0,n); }
async function ensureBlogMediaBucket(admin:ReturnType<typeof createAdminClient>){const {data,error}=await admin.storage.getBucket("blog-media");if(data&&!error)return;const {error:createError}=await admin.storage.createBucket("blog-media",{public:true,fileSizeLimit:5*1024*1024,allowedMimeTypes:["image/jpeg","image/png","image/webp","image/gif"]});if(createError&&!/already exists|duplicate/i.test(createError.message))throw new Error(`Unable to prepare blog media storage: ${createError.message}`);}
export async function saveBlogPost(formData:FormData){const user=await requireAdmin();const admin=createAdminClient();const id=text(formData,"id",80),title=text(formData,"title",180),slug=slugify(text(formData,"slug",120)||title),status=text(formData,"status",20);if(!title||!slug||!["draft","scheduled","published"].includes(status))throw new Error("Title, slug and a valid status are required.");let blocks;let rich;try{blocks=safeBlocks(JSON.parse(text(formData,"content_json",100000)));rich=sanitizeRichNode(JSON.parse(text(formData,"rich_content_json",500000)));}catch{throw new Error("The article content is invalid.");}if(!rich||rich.type!=="doc")throw new Error("Rich article content is required.");const excerpt=text(formData,"excerpt",320);if(id){const {data:old}=await admin.from("blog_posts").select("title,excerpt,content_json,rich_content_json,content_format").eq("id",id).single();if(old)await admin.from("blog_post_revisions").insert({post_id:id,editor_id:user.id,...old,change_note:text(formData,"change_note",180)});}const scheduled=text(formData,"scheduled_at",40);if(status==="scheduled"&&!scheduled)throw new Error("Choose a schedule date and time.");const row={title,slug,excerpt,content_json:blocks,rich_content_json:rich,content_format:"rich",status,author_id:user.id,assigned_author_id:text(formData,"assigned_author_id",80)||null,category_id:text(formData,"category_id",80)||null,featured_image_id:text(formData,"featured_image_id",80)||null,seo_title:text(formData,"seo_title",70),seo_description:text(formData,"seo_description",170),canonical_url:text(formData,"canonical_url",500),allow_indexing:formData.get("allow_indexing")==="on",is_featured:formData.get("is_featured")==="on",comments_enabled:formData.get("comments_enabled")==="on",related_post_ids:formData.getAll("related_post_ids").map(String).filter(Boolean).slice(0,3),scheduled_at:status==="scheduled"?new Date(scheduled).toISOString():null,published_at:status==="published"?new Date().toISOString():null,updated_at:new Date().toISOString()};const q=id?admin.from("blog_posts").update(row).eq("id",id).select("id").single():admin.from("blog_posts").insert(row).select("id").single();const {data,error}=await q;if(error)throw error;const postId=data.id;await admin.from("blog_post_tags").delete().eq("post_id",postId);const tagIds=formData.getAll("tag_ids").map(String).filter(Boolean);if(tagIds.length){const {error:e}=await admin.from("blog_post_tags").insert(tagIds.map(tag_id=>({post_id:postId,tag_id})));if(e)throw e;}revalidatePath("/blog");revalidatePath(`/blog/${slug}`);revalidatePath("/admin/blog");redirect(`/admin/blog/${postId}?saved=1`);}

export async function restoreBlogRevision(formData:FormData){await requireAdmin();const a=createAdminClient();const revisionId=text(formData,"revision_id",80);const {data:r,error}=await a.from("blog_post_revisions").select("post_id,title,excerpt,content_json,rich_content_json,content_format").eq("id",revisionId).single();if(error||!r)throw new Error("Revision not found.");const {post_id,...content}=r;const {error:e}=await a.from("blog_posts").update({...content,updated_at:new Date().toISOString()}).eq("id",post_id);if(e)throw e;revalidatePath(`/admin/blog/${post_id}`);redirect(`/admin/blog/${post_id}?restored=1`);}
export async function moderateBlogComment(formData:FormData){await requireAdmin();const id=text(formData,"id",80);const status=text(formData,"status",20);if(!["approved","spam"].includes(status))throw new Error("Invalid status.");const {error}=await createAdminClient().from("blog_comments").update({status,moderated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;revalidatePath("/admin/blog/comments");revalidatePath("/blog");}
export async function createBlogRedirect(formData:FormData){await requireAdmin();const from_path=`/${text(formData,"from_path",300).replace(/^\/+/,"")}`;const to_path=`/${text(formData,"to_path",300).replace(/^\/+/,"")}`;const status_code=Number(formData.get("status_code"))===302?302:301;if(from_path===to_path)throw new Error("Redirect paths must be different.");const {error}=await createAdminClient().from("blog_redirects").upsert({from_path,to_path,status_code},{onConflict:"from_path"});if(error)throw error;revalidatePath("/admin/blog/growth");}
export async function bulkUpdateBlogPosts(formData:FormData){await requireAdmin();const ids=formData.getAll("post_ids").map(String).filter(Boolean);const operation=text(formData,"operation",30);if(!ids.length)throw new Error("Select at least one post.");const a=createAdminClient();if(["draft","published"].includes(operation)){const row:any={status:operation,updated_at:new Date().toISOString()};if(operation==="published")row.published_at=new Date().toISOString();const {error}=await a.from("blog_posts").update(row).in("id",ids);if(error)throw error;}else if(operation==="feature"||operation==="unfeature"){const {error}=await a.from("blog_posts").update({is_featured:operation==="feature",updated_at:new Date().toISOString()}).in("id",ids);if(error)throw error;}else throw new Error("Invalid bulk operation.");revalidatePath("/admin/blog");revalidatePath("/blog");}
export async function createBlogTaxonomy(formData:FormData){ await requireAdmin(); const kind=text(formData,"kind",20); const name=text(formData,"name",80); if(!name||!["category","tag"].includes(kind)) throw new Error("Enter a valid name."); const table=kind==="category"?"blog_categories":"blog_tags"; const {error}=await createAdminClient().from(table).insert({name,slug:slugify(name)}); if(error&&!error.message.includes("duplicate")) throw error; revalidatePath("/admin/blog"); }
export async function uploadBlogMedia(formData:FormData){const user=await requireAdmin();const file=formData.get("file");if(!(file instanceof File)||!file.size)throw new Error("Choose an image.");if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type)||file.size>5*1024*1024)throw new Error("Use JPG, PNG, WebP or GIF up to 5 MB.");const admin=createAdminClient();const {error:tableError}=await admin.from("blog_media").select("id").limit(1);if(tableError)throw new Error("Blog CMS database setup is incomplete. Apply supabase/migrations/20260821_blog_cms_phase1.sql in the Supabase SQL Editor, then try again.");await ensureBlogMediaBucket(admin);const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${user.id}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await admin.storage.from("blog-media").upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw new Error(`Image upload failed: ${uploadError.message}`);const {data:profile}=await admin.from("users").select("id").eq("id",user.id).maybeSingle();const record={file_path:path,alt_text:text(formData,"alt_text",180),caption:text(formData,"caption",300),mime_type:file.type,size_bytes:file.size,uploaded_by:profile?.id||null};const {error:databaseError}=await admin.from("blog_media").insert(record);if(databaseError){await admin.storage.from("blog-media").remove([path]);throw new Error(`Image uploaded but its media record could not be saved: ${databaseError.message}`);}revalidatePath("/admin/blog/media");revalidatePath("/admin/blog");}
export async function importStarterArticles(){ const user=await requireAdmin(); const admin=createAdminClient(); const {data:cats,error}=await admin.from("blog_categories").select("id,name"); if(error)throw error; for(const p of blogPosts){const category_id=cats?.find(c=>c.name===p.category)?.id||null; const {error:e}=await admin.from("blog_posts").upsert({title:p.title,slug:p.slug,excerpt:p.description,content_json:staticBlocks(p),status:"published",author_id:user.id,category_id,published_at:"2026-08-21T00:00:00Z",updated_at:new Date().toISOString(),seo_title:p.title,seo_description:p.description},{onConflict:"slug",ignoreDuplicates:true});if(e)throw e;} revalidatePath("/admin/blog");revalidatePath("/blog"); }
