import Link from "next/link";
import { redirect } from "next/navigation";
import { ExternalLink, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { isAdminEmail } from "@/lib/admin";
import { ProfileMenu } from "@/components/profile-menu";
import { AdminSidebar } from "@/components/admin-sidebar";
export const dynamic="force-dynamic";
export default async function AdminLayout({children}:{children:React.ReactNode}){const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect("/login");const {data:profile}=await s.from("users").select("name,role").eq("id",user.id).maybeSingle();if(profile?.role!=="admin"&&!isAdminEmail(user.email))redirect("/dashboard");return <div className="min-h-screen bg-slate-50"><header className="sticky top-0 z-50 border-b border-white/10 bg-slate-950 text-white shadow-lg"><div className="mx-auto flex h-16 max-w-[1800px] items-center justify-between gap-4 px-5"><Link href="/admin" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-500 text-emerald-950"><ShieldCheck className="h-5 w-5"/></span><span><span className="block text-sm font-black leading-none">PMA Prep</span><span className="mt-1 block text-[9px] font-black uppercase tracking-[.2em] text-emerald-300">Command center</span></span></Link><div className="flex items-center gap-2"><Link href="/" target="_blank" className="hidden items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-slate-300 transition hover:bg-white/10 hover:text-white sm:flex">View website<ExternalLink className="h-3.5 w-3.5"/></Link><div className="rounded-xl border border-white/10 bg-white/5 [&_summary]:text-white [&_summary:hover]:bg-white/10"><ProfileMenu name={profile?.name||user.user_metadata?.name} email={user.email} role="admin"/></div></div></div></header><div className="admin-shell mx-auto flex max-w-[1800px] items-start"><AdminSidebar/><div className="admin-shell-content min-w-0 flex-1">{children}</div></div></div>}
