"use client";
import { useEffect, useState, useTransition } from "react";
import { Cog, Trash2 } from "lucide-react";
import { createMechanicalMcq, deleteMechanicalMcq } from "./mechanical-actions";
import { FileDropzone } from "@/components/file-dropzone";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
type Question = { id: string; image_url: string; correct_answer: string };
export function MechanicalManager({ questions }: { questions: Question[] }) {
	const [localQuestions, setLocalQuestions] = useState(questions);
	const [page, setPage] = useState(1);
	const [pending, startTransition] = useTransition();
	const [message, setMessage] = useState("");
	const [target, setTarget] = useState<string | null>(null);
	useEffect(() => setLocalQuestions(questions), [questions]);
	const pageSize = 25;
	const pageCount = Math.max(1, Math.ceil(localQuestions.length / pageSize));
	const currentPage = Math.min(page, pageCount);
	const visibleQuestions = localQuestions.slice((currentPage - 1) * pageSize, currentPage * pageSize);
	function submit(form: HTMLFormElement) { const data = new FormData(form); const options = ["A", "B", "C", "D", "E"].filter((key) => String(data.get(`option_${key}`) || "").trim()); if (options.length < 2 || !options.includes(String(data.get("correct_answer")))) { setMessage("Add at least two options and select a matching answer."); return; } startTransition(async () => { try { await createMechanicalMcq(data); setMessage("Mechanical aptitude question added."); form.reset(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to add question."); } }); }
	function remove(id: string) { const data = new FormData(); data.set("id", id); startTransition(async () => { try { await deleteMechanicalMcq(data); setLocalQuestions((current) => current.filter((question) => question.id !== id)); setMessage("Question deleted."); setTarget(null); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to delete question."); } }); }
	return <section className="mt-8"><Card><CardHeader><h2 className="flex items-center gap-2 font-black"><Cog className="h-5 w-5 text-primary" />Mechanical Aptitude</h2></CardHeader><CardContent><form encType="multipart/form-data" className="space-y-3" onSubmit={(event) => { event.preventDefault(); submit(event.currentTarget); }}><input name="question" placeholder="Optional question text" /><FileDropzone name="image" accept="image/png,image/jpeg,image/webp" label="Drop mechanical diagram here" hint="PNG, JPG, or WEBP up to 5 MB" required /><div className="grid gap-3 sm:grid-cols-2">{["A", "B", "C", "D", "E"].map((key) => <input key={key} name={`option_${key}`} placeholder={`Option ${key} (optional E)`} />)}</div><select name="correct_answer" defaultValue="A">{["A", "B", "C", "D", "E"].map((key) => <option key={key}>{key}</option>)}</select><Button disabled={pending}>{pending ? "Saving..." : "Publish question"}</Button></form>{message && <p className="mt-4 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}<div className="mt-6 divide-y rounded-xl border">{visibleQuestions.map((question, index) => <div className="flex items-center gap-3 p-3" key={question.id}><img className="h-16 w-24 rounded-lg object-contain" src={question.image_url} alt="Mechanical aptitude question" /><p className="flex-1 text-sm font-semibold">Question {(currentPage - 1) * pageSize + index + 1} · Answer {question.correct_answer}</p><Button type="button" variant="outline" size="sm" onClick={() => setTarget(question.id)} disabled={pending}><Trash2 className="h-4 w-4" /></Button></div>)}</div>{!localQuestions.length && <p className="mt-4 text-sm text-slate-500">No mechanical aptitude questions yet.</p>}<div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t pt-4"><p className="text-sm text-slate-500">Page {currentPage} of {pageCount}</p><div className="flex gap-2"><Button type="button" size="sm" variant="outline" onClick={() => setPage((value) => Math.max(1, value - 1))} disabled={currentPage === 1}>Previous</Button><Button type="button" size="sm" variant="outline" onClick={() => setPage((value) => Math.min(pageCount, value + 1))} disabled={currentPage === pageCount}>Next</Button></div></div></CardContent></Card>{target && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h3 className="text-lg font-black">Delete this mechanical aptitude question?</h3><p className="mt-2 text-sm text-slate-500">The question and uploaded image will be permanently removed.</p><div className="mt-6 flex justify-end gap-3"><Button variant="outline" onClick={() => setTarget(null)}>Cancel</Button><Button disabled={pending} onClick={() => remove(target)}>{pending ? "Deleting..." : "Delete"}</Button></div></div></div>}</section>;
}
