"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { isAdminEmail } from "@/lib/admin";
import { sanitizeRichNode } from "@/lib/rich-content";
import { slugify } from "@/lib/blog-cms";

async function adminUser(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();const{data:profile}=user?await supabase.from("users").select("role").eq("id",user.id).single():{data:null};if(!user||(profile?.role!=="admin"&&!isAdminEmail(user.email)))throw new Error("Unauthorized");return user}

export async function createGtoLesson(form:FormData){const user=await adminUser();const title=String(form.get("title")||"").trim();const excerpt=String(form.get("excerpt")||"").trim().slice(0,320);const category=String(form.get("category")||"");const status=String(form.get("status")||"draft");const valid=["Group Planning","Command Task","PGT / HGT","Individual Obstacles"];if(!title||!excerpt||!valid.includes(category)||!["draft","published"].includes(status))throw new Error("Complete the lesson title, summary and category.");let content:unknown;try{content=JSON.parse(String(form.get("rich_content_json")||""))}catch{throw new Error("Lesson content is invalid.")}const rich=sanitizeRichNode(content);if(!rich)throw new Error("Add valid lesson content.");const image=form.get("featured_image"),pdf=form.get("pdf");if(!(image instanceof File)||!image.size||!["image/jpeg","image/png","image/webp"].includes(image.type)||image.size>5*1024*1024)throw new Error("Choose a JPG, PNG or WebP featured image up to 5 MB.");if(pdf instanceof File&&pdf.size&&(pdf.type!=="application/pdf"||pdf.size>5*1024*1024))throw new Error("The optional lesson PDF must be no larger than 5 MB.");const admin=createAdminClient(),base=`${user.id}/lessons/${crypto.randomUUID()}`,imagePath=`${base}-${image.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const{error:imageError}=await admin.storage.from("gto-assets").upload(imagePath,image,{contentType:image.type});if(imageError)throw imageError;let pdfPath:string|null=null;if(pdf instanceof File&&pdf.size){pdfPath=`${base}-${pdf.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const{error}=await admin.storage.from("gto-assets").upload(pdfPath,pdf,{contentType:"application/pdf"});if(error){await admin.storage.from("gto-assets").remove([imagePath]);throw error}}const{error}=await admin.from("gto_lessons").insert({title,slug:slugify(String(form.get("slug")||title)),excerpt,category,status,rich_content_json:rich,featured_image_path:imagePath,pdf_path:pdfPath,author_id:user.id,published_at:status==="published"?new Date().toISOString():null});if(error){await admin.storage.from("gto-assets").remove([imagePath,...(pdfPath?[pdfPath]:[])]);throw new Error(`Could not save GTO lesson: ${error.message}. Apply the GTO lessons migration first.`)}revalidatePath("/admin/gto");revalidatePath("/gto");revalidatePath("/gto/lessons")}

export async function deleteGtoLesson(form:FormData){await adminUser();const id=String(form.get("id")||"");const a=createAdminClient();const{data,error:read}=await a.from("gto_lessons").select("featured_image_path,pdf_path").eq("id",id).single();if(read||!data)throw new Error("GTO lesson not found.");const{error}=await a.from("gto_lessons").delete().eq("id",id);if(error)throw error;const paths=[data.featured_image_path,data.pdf_path].filter(Boolean) as string[];if(paths.length)await a.storage.from("gto-assets").remove(paths);revalidatePath("/admin/gto");revalidatePath("/gto/lessons")}
