import Link from "next/link";
import { redirect } from "next/navigation";
import { BookOpen, Eye } from "lucide-react";
import { Button } from "@/components/ui/button";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { isAdminEmail } from "@/lib/admin";
import { GtoLessonEditor } from "@/components/gto-lesson-editor";
import { LessonAdminActions } from "@/components/lesson-admin-actions";
import { createGtoLesson, deleteGtoLesson } from "./actions";

export default async function GtoAdmin(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();const{data:profile}=user?await supabase.from("users").select("role").eq("id",user.id).single():{data:null};if(!user||(profile?.role!=="admin"&&!isAdminEmail(user.email)))redirect("/dashboard");const admin=createAdminClient();const{data:lessons}=await admin.from("gto_lessons").select("id,title,category,status,slug,created_at").order("created_at",{ascending:false});return <main className="mx-auto max-w-6xl px-5 py-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-primary">GTO content studio</p><h1 className="mt-1 text-3xl font-black">Visual GTO Lessons</h1><p className="mt-2 max-w-2xl text-slate-500">This is the single publishing system for Group Planning, Command Task, PGT/HGT and Individual Obstacles.</p></div><div className="flex gap-2"><Button asChild variant="outline"><Link href="/gto/lessons"><Eye className="mr-2 h-4 w-4"/>View lessons</Link></Button><Button asChild variant="outline"><Link href="/admin">Back to admin</Link></Button></div></div><section className="mt-8 rounded-3xl border border-emerald-200 bg-emerald-50/60 p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-600 text-white"><BookOpen className="h-5 w-5"/></div><div><p className="text-xs font-black uppercase tracking-widest text-emerald-700">New lesson</p><h2 className="text-2xl font-black">Publish complete GTO guidance</h2></div></div><GtoLessonEditor action={createGtoLesson}/></section><section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-primary">Lesson library</p><h2 className="mt-1 text-2xl font-black">All GTO content</h2></div><span className="rounded-full bg-slate-200 px-3 py-1 text-xs font-bold text-slate-600">{lessons?.length||0} lessons</span></div>{(lessons||[]).length?<div className="mt-5 grid gap-3 sm:grid-cols-2">{lessons?.map(x=><div key={x.id} className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><span className="text-xs font-black uppercase tracking-wider text-emerald-700">{x.category}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${x.status==="published"?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800"}`}>{x.status}</span></div><h3 className="mt-2 font-black">{x.title}</h3><LessonAdminActions id={x.id} title={x.title} status={x.status} href={`/gto/lessons/${x.slug}`} deleteAction={deleteGtoLesson}/></div>)}</div>:<div className="mt-5 rounded-2xl border border-dashed bg-white p-8 text-center text-slate-500">No lessons yet. Use the publisher above to add the first task guide.</div>}</section></main>}
