import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, Clock3, ImageIcon } from "lucide-react";
import { getPublicPosts } from "@/lib/blog-data";
import { Card, CardContent } from "@/components/ui/card";
import { NewsletterSignup } from "@/components/newsletter-signup";
import { AdSlot } from "@/components/ad-slot";
export const metadata:Metadata={title:"PMA Initial & ISSB Preparation Blog | PMA Prep",description:"Practical guides for PMA initial tests, verbal and non-verbal intelligence, ISSB psychology, GTO tasks and interviews."};
export const dynamic="force-dynamic";
export default async function BlogPage(){const posts=await getPublicPosts();return <main><section className="bg-slate-950 px-5 py-16 text-white sm:py-20"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-300">Preparation library</p><h1 className="mt-3 max-w-3xl text-5xl font-black">Clear guidance for PMA Initial and ISSB.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Practical explanations, preparation methods and common mistakes—written to help you take the next useful action.</p></div></section><section className="mx-auto max-w-7xl px-5 py-14"><AdSlot slot={process.env.NEXT_PUBLIC_ADSENSE_CONTENT_SLOT} className="mb-10 rounded-xl border bg-white p-3"/><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{posts.map(post=><Link href={`/blog/${post.slug}`} key={post.slug} className="group"><Card className="h-full overflow-hidden transition group-hover:-translate-y-1 group-hover:border-emerald-300 group-hover:shadow-xl"><div className="relative aspect-[16/9] overflow-hidden bg-slate-100">{post.featured_image?.public_url?<img src={post.featured_image.public_url} alt={post.featured_image.alt_text||post.title} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.04]"/>:<div className="grid h-full place-items-center bg-gradient-to-br from-emerald-50 to-slate-100 text-emerald-700"><ImageIcon className="h-8 w-8"/></div>}<span className="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1 text-xs font-black text-emerald-800 shadow-sm">{post.category?.name||"Guide"}</span></div><CardContent className="flex min-h-64 flex-col pt-6"><div className="flex items-center justify-between text-xs font-bold text-slate-400"><span className="flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>{Math.max(3,Math.ceil(post.content_json.length*.7))} min read</span><BookOpen className="h-4 w-4 text-emerald-600"/></div><h2 className="mt-4 text-xl font-black leading-7">{post.title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-slate-600">{post.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary">Read guide <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></CardContent></Card></Link>)}</div><div className="mt-12"><NewsletterSignup/></div></section></main>}
