import Link from "next/link";
import { ArrowRight, BookOpen, Brain, Check, ChevronRight, ClipboardCheck, Coins, Flag, ImageIcon, LockKeyhole, MessageSquareText, Sparkles, Target, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ReviewsSlider } from "@/components/reviews-slider";
import { PmaIntakeSection } from "@/components/pma-intake-section";
import { HomeValueSlider } from "@/components/home-value-slider";
import { AnimatedSignal } from "@/components/animated-signal";
import { accessPlans, planDiscount } from "@/lib/plans";
import { getPublicPosts } from "@/lib/blog-data";

const paths = [
  { title: "PMA Initial", eyebrow: "Build the foundation", description: "Academic MCQs, verbal and non-verbal intelligence, personality, medical, physical and interview preparation.", icon: ClipboardCheck, plan: accessPlans.initial, href: "/signup?plan=initial", features: ["Strict timed mock tests", "Academic question bank", "Progress and score history"] },
  { title: "ISSB Preparation", eyebrow: "Develop officer potential", description: "Psychological testing, GTO scenarios, individual obstacles, group planning and interview practice.", icon: Flag, plan: accessPlans.issb, href: "/signup?plan=issb", features: ["WAT, SCT, TAT and SDT", "GTO task library", "Interview preparation"] },
];

const steps = [
  { number: "01", title: "Create your account", text: "Start with 100 credits—enough to explore real timed practice before choosing a pass." },
  { number: "02", title: "Choose your track", text: "Prepare for PMA Initial, ISSB, or combine both in one 90-day plan." },
  { number: "03", title: "Practise with structure", text: "Follow tutorials, complete timed sessions and review progress instead of studying randomly." },
  { number: "04", title: "Improve the next weakness", text: "Use scores, feedback and participation history to decide what to practise next." },
];

export const dynamic = "force-dynamic";

export default async function Home() {
  const posts = await getPublicPosts();
  return <HomeContent posts={posts} />;
}

function HomeContent({ posts }: { posts: Awaited<ReturnType<typeof getPublicPosts>> }) {
  return <main className="bg-white">
    <section className="relative isolate overflow-hidden bg-slate-950 text-white">
      <div className="absolute inset-0 -z-10 opacity-50 [background-image:radial-gradient(circle_at_80%_15%,rgba(16,185,129,.4),transparent_28%),radial-gradient(circle_at_15%_85%,rgba(14,165,233,.18),transparent_25%)]" />
      <div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:py-24 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:py-28">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-emerald-300/25 bg-emerald-300/10 px-4 py-2 text-sm font-bold text-emerald-200"><Sparkles className="h-4 w-4" />100 free credits with every account</div><h1 className="mt-7 max-w-4xl text-5xl font-black leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl">Prepare for selection with a plan you can measure.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">One focused platform for PMA Initial and ISSB preparation—timed tests, psychological practice, GTO scenarios, interview guidance and progress tracking.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg"><Link href="/signup">Start with 100 credits <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild size="lg" variant="outline" className="border-white/20 bg-white/10 text-white hover:bg-white/20"><Link href="/issb-test-preparation-guide">Read the ISSB guide</Link></Button></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-sm text-slate-400">{["No card required", "Private progress", "Admin-verified payments"].map(item => <span key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-400" />{item}</span>)}</div></div>
        <div className="relative"><div className="rounded-[2rem] border border-white/10 bg-white/[.07] p-5 shadow-2xl backdrop-blur sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Your preparation wallet</p><p className="mt-2 text-4xl font-black">100 <span className="text-lg font-semibold text-slate-300">credits</span></p></div><div className="grid h-14 w-14 place-items-center rounded-2xl bg-amber-400 text-slate-950"><Coins className="h-7 w-7" /></div></div><div className="mt-7 grid gap-3"><PracticeRow icon={Target} title="Initial mock test" cost="25 credits" /><PracticeRow icon={Brain} title="ISSB psychology session" cost="15 credits" /><PracticeRow icon={BookOpen} title="Guides and public resources" cost="Free" /></div><div className="mt-6 rounded-xl border border-emerald-300/20 bg-emerald-300/10 p-4 text-sm leading-6 text-emerald-100"><strong>Active pass?</strong> Normal practice in that course does not use your credits until the pass expires.</div></div></div>
      </div>
    </section>
    <PmaIntakeSection />

    <HomeValueSlider />

    <section className="border-b bg-white"><div className="mx-auto max-w-7xl px-5 py-7"><div className="grid grid-cols-2 divide-x divide-slate-200 sm:grid-cols-4"><AnimatedSignal value="1,000+" label="candidates preparing*" /><AnimatedSignal value="5,000+" label="practice sessions*" /><AnimatedSignal value="2" label="preparation tracks" /><AnimatedSignal value="100" label="starter credits per account" /></div><p className="mt-4 text-center text-[11px] font-medium text-slate-400"></p></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:py-20"><div className="flex flex-wrap items-end justify-between gap-5"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[.18em] text-primary">Preparation blog</p><h2 className="mt-3 text-4xl font-black tracking-tight">Read smarter before you practise.</h2><p className="mt-4 text-lg leading-8 text-slate-600">Clear guidance for PMA Initial and ISSB preparation, written around the next useful action.</p></div><Link href="/blog" className="inline-flex items-center gap-2 text-sm font-black text-primary">View all guides <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-9 grid gap-5 md:grid-cols-3">{posts.slice(0,3).map(post => <Link href={`/blog/${post.slug}`} key={post.slug} className="group"><Card className="h-full overflow-hidden border-slate-200 transition group-hover:-translate-y-1 group-hover:border-emerald-300 group-hover:shadow-xl"><div className="relative aspect-[16/9] overflow-hidden bg-slate-100">{post.featured_image?.public_url?<img src={post.featured_image.public_url} alt={post.featured_image.alt_text||post.title} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.04]"/>:<div className="grid h-full place-items-center bg-gradient-to-br from-emerald-50 to-slate-100 text-emerald-700"><ImageIcon className="h-8 w-8"/></div>}</div><CardContent className="flex h-full flex-col p-6"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-black text-emerald-800">{post.category?.name || "Guide"}</span><BookOpen className="h-4 w-4 text-emerald-600" /></div><h3 className="mt-5 text-xl font-black leading-7">{post.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-slate-600">{post.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary">Read guide <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></CardContent></Card></Link>)}</div></section>

    <section className="bg-slate-950 py-16 text-white sm:py-20"><div className="mx-auto max-w-7xl px-5"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-300">A calmer process</p><h2 className="mt-3 text-4xl font-black">From signup to focused improvement.</h2><p className="mt-4 leading-7 text-slate-300">The platform is designed around the next useful action—not an overwhelming library of disconnected material.</p></div><div className="grid gap-3 sm:grid-cols-2">{steps.map(step => <div key={step.number} className="rounded-2xl border border-white/10 bg-white/[.06] p-5"><p className="text-sm font-black text-emerald-300">{step.number}</p><h3 className="mt-3 text-lg font-black">{step.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{step.text}</p></div>)}</div></div></div></section>

    <section id="pricing" className="mx-auto max-w-7xl scroll-mt-24 px-5 py-16 sm:py-20"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-black uppercase tracking-[.18em] text-primary">Introductory pricing</p><h2 className="mt-3 text-4xl font-black">Save while the platform grows.</h2><p className="mt-4 text-slate-600">The crossed-out amount is the regular price. Passes begin after payment approval and unused starter credits remain in your account.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{Object.values(accessPlans).map(plan => <Card key={plan.code} className={`relative ${plan.code === "complete" ? "border-emerald-500 shadow-xl ring-2 ring-emerald-100" : ""}`}>{plan.code === "complete" && <span className="absolute right-5 top-0 -translate-y-1/2 rounded-full bg-amber-400 px-3 py-1 text-xs font-black text-slate-950">BEST VALUE</span>}<CardContent className="flex h-full flex-col p-7"><div className="flex items-center justify-between gap-3"><p className="text-sm font-black text-primary">{plan.name}</p><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-black text-emerald-800">SAVE {planDiscount(plan)}%</span></div><p className="mt-5 text-base font-bold text-slate-400 line-through">PKR {plan.originalPrice.toLocaleString()}</p><p className="mt-1 text-4xl font-black">PKR {plan.price.toLocaleString()}</p><p className="mt-2 text-sm font-semibold text-emerald-700">You save PKR {(plan.originalPrice-plan.price).toLocaleString()}</p><p className="mt-1 text-sm text-slate-500">{plan.days} days from approval</p><div className="my-6 border-t" /><ul className="flex-1 space-y-3 text-sm text-slate-700">{(plan.scopes.length === 2 ? ["Complete PMA Initial access", "Complete ISSB access", "Normal practice without credit charges", "Progress and score history"] : plan.scopes[0] === "initial" ? ["All PMA Initial modules", "Timed academic and intelligence tests", "Normal practice without credit charges", "Progress and score history"] : ["Psychological test practice", "GTO and obstacle preparation", "Interview preparation", "Normal practice without credit charges"]).map(feature => <li className="flex gap-2" key={feature}><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{feature}</li>)}</ul><Button asChild className="mt-7" variant={plan.code === "complete" ? "default" : "outline"}><Link href={`/signup?plan=${plan.code}`}>Get discounted access</Link></Button></CardContent></Card>)}</div></section>

    <section className="bg-emerald-50"><div className="mx-auto grid max-w-7xl gap-7 px-5 py-14 lg:grid-cols-[1fr_auto] lg:items-center"><div className="flex gap-4"><div className="hidden h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white text-primary shadow-sm sm:flex"><MessageSquareText className="h-6 w-6" /></div><div><p className="text-sm font-black uppercase tracking-wider text-primary">New to ISSB?</p><h2 className="mt-2 text-3xl font-black">Understand the complete process before practising.</h2><p className="mt-3 max-w-2xl leading-7 text-slate-600">Our public guide explains the five-day schedule, psychological domain, GTO tasks, interview and preparation strategy.</p></div></div><Button asChild size="lg"><Link href="/issb-test-preparation-guide">Open the ISSB guide <ChevronRight className="ml-2 h-4 w-4" /></Link></Button></div></section>

    <ReviewsSlider />

    <section className="mx-auto max-w-4xl px-5 py-16 text-center sm:py-20"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-slate-950 text-emerald-300"><Users className="h-7 w-7" /></div><h2 className="mt-6 text-4xl font-black">Start preparing without guessing.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-600">Create your account, use the 100 included credits and choose a paid pass only when you are ready for full-course access.</p><Button asChild size="lg" className="mt-7"><Link href="/signup">Create free account <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><p className="mt-4 flex items-center justify-center gap-2 text-xs text-slate-500"><LockKeyhole className="h-3.5 w-3.5" />Your paid content and progress are account-protected.</p></section>
  </main>;
}

function PracticeRow({ icon: Icon, title, cost }: { icon: typeof Target; title: string; cost: string }) { return <div className="flex items-center gap-3 rounded-xl border border-white/10 bg-slate-950/40 p-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-white/10"><Icon className="h-5 w-5 text-emerald-300" /></div><p className="flex-1 text-sm font-bold">{title}</p><span className="text-xs font-semibold text-slate-300">{cost}</span></div>; }
