import { redirect } from "next/navigation";
import { Activity, BookOpen, CheckCircle2, LockKeyhole, UserRound } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { updatePassword, updateProfile } from "./actions";

export const dynamic = "force-dynamic";

export default async function ProfilePage({ searchParams }: { searchParams: Promise<{ message?: string }> }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");
  const [{ data: profile }, { data: attempts }, { data: activity }] = await Promise.all([
    supabase.from("users").select("name,email,role,enrolled_course,progress,preferences,avatar_url,created_at").eq("id", user.id).single(),
    supabase.from("practice_attempts").select("module,score,completed_at").eq("user_id", user.id).order("completed_at", { ascending: false }).limit(5),
    supabase.from("daily_activity").select("activity_date,minutes").eq("user_id", user.id).order("activity_date", { ascending: false }).limit(5),
  ]);
  const completion = Math.min(100, Number(profile?.progress || 0));
  const params = await searchParams;
  return <main className="mx-auto max-w-6xl px-5 py-10"><div className="mb-8"><p className="text-sm font-bold uppercase tracking-wider text-primary">Account center</p><h1 className="mt-2 text-3xl font-black">Your profile</h1><p className="mt-2 text-slate-500">Keep your candidate details and study preferences current.</p></div>
    {params.message && <div className="mb-6 rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-800">{params.message}</div>}
    <div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><Card><CardContent className="pt-6"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-primary text-xl font-black text-white">{(profile?.name || user.email || "U").slice(0, 1).toUpperCase()}</div><div><h2 className="text-xl font-black">{profile?.name}</h2><p className="text-sm text-slate-500">{profile?.email || user.email}</p><span className="mt-2 inline-flex rounded-full bg-green-50 px-2.5 py-1 text-xs font-bold text-primary">{profile?.role === "admin" ? "Administrator" : "Student"}</span></div></div><div className="mt-8"><div className="flex justify-between text-sm font-semibold"><span>Preparation progress</span><span className="text-primary">{completion}%</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-primary" style={{ width: `${completion}%` }} /></div></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-4"><BookOpen className="h-5 w-5 text-primary" /><p className="mt-3 text-xs text-slate-500">Enrolled course</p><p className="mt-1 font-bold">{profile?.enrolled_course || "PMA Initial"}</p></div><div className="rounded-xl bg-slate-50 p-4"><Activity className="h-5 w-5 text-primary" /><p className="mt-3 text-xs text-slate-500">Recent sessions</p><p className="mt-1 font-bold">{attempts?.length || 0} recorded</p></div></div></CardContent></Card>
      <div className="space-y-6"><Card><CardHeader><h2 className="flex items-center gap-2 text-lg font-black"><UserRound className="h-5 w-5 text-primary" />Personal details</h2></CardHeader><CardContent><form action={updateProfile} className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><label htmlFor="name">Full name</label><input id="name" name="name" defaultValue={profile?.name || ""} required /></div><div className="space-y-1.5"><label htmlFor="email">Email</label><input id="email" value={profile?.email || user.email || ""} disabled /></div><div className="space-y-1.5"><label htmlFor="enrolled_course">Enrolled course</label><select id="enrolled_course" name="enrolled_course" defaultValue={profile?.enrolled_course || "PMA Initial"}><option>PMA Initial</option><option>ISSB</option></select></div><div className="space-y-1.5"><label htmlFor="language">Language</label><select id="language" name="language" defaultValue={(profile?.preferences as { language?: string } | null)?.language || "en"}><option value="en">English</option><option value="ur">Urdu</option></select></div><div className="space-y-1.5"><label htmlFor="weekly_goal">Weekly study sessions</label><input id="weekly_goal" name="weekly_goal" type="number" min="1" max="30" defaultValue={(profile?.preferences as { weekly_goal?: number } | null)?.weekly_goal || 5} /></div><div className="sm:col-span-2"><Button type="submit">Save changes</Button></div></form></CardContent></Card>
      <Card id="settings"><CardHeader><h2 className="flex items-center gap-2 text-lg font-black"><LockKeyhole className="h-5 w-5 text-primary" />Security</h2></CardHeader><CardContent><form action={updatePassword} className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="flex-1 space-y-1.5"><label htmlFor="password">New password</label><input id="password" name="password" type="password" minLength={6} placeholder="At least 6 characters" required /></div><Button type="submit" variant="outline">Update password</Button></form></CardContent></Card>
      <Card><CardHeader><h2 className="flex items-center gap-2 text-lg font-black"><CheckCircle2 className="h-5 w-5 text-primary" />Recent activity</h2></CardHeader><CardContent><div className="space-y-3">{attempts?.map((attempt) => <div className="flex items-center justify-between border-b pb-3 text-sm last:border-0 last:pb-0" key={`${attempt.module}-${attempt.completed_at}`}><span className="font-semibold">{attempt.module}</span><span className="text-slate-500">{Number(attempt.score)}% · {new Date(attempt.completed_at).toLocaleDateString()}</span></div>)}{!attempts?.length && <p className="text-sm text-slate-500">Your completed practice will appear here.</p>}</div></CardContent></Card></div></div></main>;
}