"use client";

import { useEffect, useState, useTransition } from "react";
import { CheckCircle2, Users } from "lucide-react";
import { completeIssbExercise } from "@/app/issb-path/actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

const exercises = [
  { id: "Group Discussion", title: "Group discussion", time: 300, scenario: "Your group has been asked to improve safety and cleanliness in a flood-affected village with limited resources. Agree on three immediate priorities.", steps: ["Listen to the problem and clarify the goal.", "Offer one practical idea with a reason.", "Invite another member to contribute.", "Help the group reach a realistic conclusion."] },
  { id: "Command Task", title: "Command task", time: 420, scenario: "Your team must move essential supplies across a gap using a plank, rope and two drums. One team member has a minor ankle injury.", steps: ["State the objective and check safety risks.", "Assign clear roles according to the available resources.", "Explain the sequence before starting.", "Adapt calmly if the first plan fails."] },
  { id: "Group Planning Exercise", title: "Group planning exercise", time: 600, scenario: "A school bus is delayed near a remote road at dusk. There are 18 students, one first-aid kit, two phones with limited battery, and rain is expected.", steps: ["Separate facts, risks and time limits.", "Set priorities: safety, communication and transport.", "Allocate roles and resources fairly.", "Present a short, coordinated plan to the group."] },
];
export function GroupTaskSimulator() {
  const [selected, setSelected] = useState(0); const exercise = exercises[selected]; const [checked, setChecked] = useState<boolean[]>([]); const [note, setNote] = useState(""); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  useEffect(() => { setChecked(Array(exercise.steps.length).fill(false)); setNote(""); setMessage(""); }, [exercise]);
  const finish = () => startTransition(async () => { try { await completeIssbExercise(`Group Task: ${exercise.id}`, checked.filter(Boolean).length === exercise.steps.length ? 85 : 70); setMessage("Practice saved to your ISSB Path report."); } catch { setMessage("Unable to save this session. Please try again."); } });
  return <main className="mx-auto max-w-5xl px-5 py-10"><div className="rounded-3xl bg-slate-950 px-6 py-9 text-white"><p className="flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-emerald-300"><Users className="h-4 w-4" />ISSB Path</p><h1 className="mt-3 text-4xl font-black">Group task simulator</h1><p className="mt-3 max-w-2xl text-slate-300">Practise how you would think, communicate and support a team. Use paper for your plan; this screen guides the exercise.</p></div><div className="mt-7 flex flex-wrap gap-2">{exercises.map((item, index) => <Button key={item.id} variant={selected === index ? "default" : "outline"} onClick={() => setSelected(index)}>{item.title}</Button>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><Card><CardHeader><p className="text-sm font-bold text-primary">SCENARIO</p><h2 className="text-2xl font-black">{exercise.title}</h2></CardHeader><CardContent><p className="rounded-2xl bg-slate-50 p-5 leading-7 text-slate-700">{exercise.scenario}</p><h3 className="mt-6 font-bold">Your approach</h3><div className="mt-3 space-y-3">{exercise.steps.map((step, index) => <label key={step} className="flex cursor-pointer items-start gap-3 rounded-xl border p-4 text-slate-700"><input type="checkbox" checked={Boolean(checked[index])} onChange={() => setChecked(values => values.map((value, i) => i === index ? !value : value))} className="mt-1 h-4 w-4" /><span>{step}</span></label>)}</div><label className="mt-6 block">Brief plan (optional)<textarea className="mt-2" rows={5} value={note} onChange={e => setNote(e.target.value)} placeholder="Write your plan on paper, or make a quick note here…" /></label></CardContent></Card><Card className="h-fit"><CardContent className="pt-6"><p className="text-sm font-bold uppercase tracking-wider text-slate-500">Practice guide</p><h3 className="mt-2 text-xl font-black">Work through your plan</h3><p className="mt-4 text-sm leading-6 text-slate-500">There is no fixed timer for group tasks. Focus on clear communication, practical decisions and supporting the team.</p><Button className="mt-6 w-full" variant="outline" disabled={pending} onClick={finish}><CheckCircle2 className="mr-2 h-4 w-4" />{pending ? "Saving…" : "Complete practice"}</Button>{message && <p className="mt-4 rounded-xl bg-green-50 p-3 text-sm text-green-800">{message}</p>}</CardContent></Card></div></main>;
}
