"use client";
import { useMemo, useState } from "react";
import { RichTextEditor } from "@/components/rich-text-editor";
import { FileDropzone } from "@/components/file-dropzone";
import { slugify } from "@/lib/blog-cms";
import type { RichNode } from "@/lib/rich-content";
const empty:RichNode={type:"doc",content:[{type:"heading",attrs:{level:2},content:[{type:"text",text:"Task overview"}]},{type:"paragraph",content:[{type:"text",text:"Explain the task, layout and objective."}]},{type:"heading",attrs:{level:2},content:[{type:"text",text:"Rules and recommended approach"}]},{type:"paragraph",content:[]}]};
export function GtoLessonEditor({action}:{action:(form:FormData)=>void}){const [title,setTitle]=useState(""),[slug,setSlug]=useState(""),[rich,setRich]=useState<RichNode>(empty);const payload=useMemo(()=>JSON.stringify(rich),[rich]);return <form action={action} className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_330px]"><input type="hidden" name="rich_content_json" value={payload}/><section className="space-y-5"><div className="rounded-2xl border bg-white p-5"><label className="text-xs font-black uppercase tracking-wider text-slate-500">Lesson title</label><input name="title" required value={title} onChange={e=>{setTitle(e.target.value);setSlug(slugify(e.target.value))}} placeholder="Example: How to approach the Command Task" className="mt-2 border-0 px-0 text-3xl font-black"/><label className="mt-4 block text-xs font-black uppercase tracking-wider text-slate-500">URL</label><div className="mt-2 flex items-center rounded-xl border px-3 text-sm text-slate-400">/gto/lessons/<input name="slug" value={slug} onChange={e=>setSlug(slugify(e.target.value))} className="border-0 px-1"/></div><label className="mt-4 block text-xs font-black uppercase tracking-wider text-slate-500">Short summary</label><textarea name="excerpt" required maxLength={320} className="mt-2 min-h-24" placeholder="What will the candidate understand after this lesson?"/></div><RichTextEditor initial={rich} onChange={setRich}/></section><aside className="space-y-5"><Panel title="Publish"><select name="status" defaultValue="draft"><option value="draft">Save as draft</option><option value="published">Publish now</option></select><button className="mt-4 w-full rounded-xl bg-emerald-600 px-4 py-3 font-black text-white">Save GTO lesson</button></Panel><Panel title="Lesson category"><select name="category" required defaultValue=""><option value="" disabled>Select category</option><option>Group Planning</option><option>Command Task</option><option>PGT / HGT</option><option>Individual Obstacles</option></select></Panel><Panel title="Featured diagram"><FileDropzone name="featured_image" accept="image/jpeg,image/png,image/webp" imagePreset="diagram" required label="Upload lesson image" hint="JPG, PNG or WebP · optimized automatically"/></Panel><Panel title="Optional revision PDF"><FileDropzone name="pdf" accept="application/pdf,.pdf" label="Attach supporting PDF" hint="Optional PDF up to 5 MB"/></Panel></aside></form>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-black">{title}</h2>{children}</div>}
