export type BlogPost = { slug: string; title: string; description: string; category: "PMA Initial" | "ISSB"; readTime: string; updated: string; sections: { heading: string; paragraphs: string[]; bullets?: string[] }[] };

export const blogPosts: BlogPost[] = [
  { slug: "pma-long-course-eligibility-guide", title: "PMA Long Course Eligibility Guide", description: "Understand the common education, age, nationality and physical requirements candidates should verify before applying.", category: "PMA Initial", readTime: "7 min", updated: "August 21, 2026", sections: [
    { heading: "Start with the official advertisement", paragraphs: ["Eligibility can change between courses. Treat the current Pakistan Army advertisement and registration portal as the final authority, especially for age relaxations, education combinations and serving personnel.", "Use a preparation website to understand the process, but confirm every personal eligibility decision from the official notice before submitting an application."] },
    { heading: "Information to verify", paragraphs: ["Prepare your academic record and calculate your age on the stated cutoff date."], bullets: ["Required qualification and minimum marks", "Age on the official cutoff date", "Marital-status conditions", "Nationality and domicile requirements", "Height, weight and medical standards", "Rules for serving personnel and graduates"] },
    { heading: "Documents to prepare", paragraphs: ["Keep originals and readable copies of identity, domicile and academic documents. Make sure names, dates and spellings agree across records. Resolve discrepancies early rather than at the selection centre."] },
    { heading: "What comes after registration", paragraphs: ["Eligible applicants generally move through initial testing, physical and medical checks, interview stages and ISSB where applicable. Begin academic and intelligence practice before the test date appears on your slip."] },
  ] },
  { slug: "pma-initial-test-syllabus-and-pattern", title: "PMA Initial Test Syllabus and Preparation Pattern", description: "A practical breakdown of academic, verbal and non-verbal preparation for the PMA initial assessment.", category: "PMA Initial", readTime: "8 min", updated: "August 21, 2026", sections: [
    { heading: "The purpose of initial testing", paragraphs: ["Initial testing checks whether a candidate has the academic foundation, reasoning speed and basic suitability to continue. The pace matters: knowing a method is not enough if every answer takes too long."] },
    { heading: "Academic preparation areas", paragraphs: ["Build a balanced revision plan instead of studying only general knowledge."], bullets: ["English vocabulary, grammar and sentence completion", "Percentages, ratios, averages and basic algebra", "Pakistan Studies and Islamic Studies", "General science and everyday knowledge", "Current national and international affairs"] },
    { heading: "Intelligence preparation", paragraphs: ["Verbal questions commonly use analogies, series, coding and relationships. Non-verbal questions use shapes, rotations and patterns. Learn the relationship first, then improve speed through timed sets."] },
    { heading: "A useful weekly routine", paragraphs: ["Complete short topic sessions during the week and one full timed mock at the weekend. Review every incorrect answer and label the reason: knowledge gap, misunderstood pattern or time pressure."] },
  ] },
  { slug: "verbal-intelligence-test-preparation", title: "Verbal Intelligence Test Preparation for PMA Candidates", description: "Methods for analogies, number series, coding, odd-one-out and relationship questions under time pressure.", category: "PMA Initial", readTime: "7 min", updated: "August 21, 2026", sections: [
    { heading: "Identify the question family", paragraphs: ["Most verbal questions become easier when you name their structure. Decide whether the item is testing sequence, classification, analogy, coding or a family relationship before calculating an answer."] },
    { heading: "Series and analogies", paragraphs: ["For number series, compare differences, ratios and alternating operations. For analogies, state the exact relationship in simple words before applying it to the second pair."] },
    { heading: "Coding and relationships", paragraphs: ["Write small position changes clearly while learning, then practise doing them mentally. In family questions, draw a tiny tree instead of holding every relationship in memory."] },
    { heading: "Improve speed safely", paragraphs: ["Use three rounds: untimed accuracy, moderate timed sets and strict mock conditions. Speed gained through guessing does not transfer reliably to the real test."] },
  ] },
  { slug: "non-verbal-intelligence-test-guide", title: "Non-Verbal Intelligence Test Guide", description: "Learn how to inspect rotations, sequences, reflections and changing-shape patterns efficiently.", category: "PMA Initial", readTime: "7 min", updated: "August 21, 2026", sections: [
    { heading: "Observe one feature at a time", paragraphs: ["Do not stare at the whole diagram. Track direction, number, position, shading and size separately. One feature may rotate while another alternates."] },
    { heading: "Common transformations", paragraphs: ["Practise recognising the most frequent visual operations."], bullets: ["Clockwise and anticlockwise rotation", "Horizontal and vertical reflection", "Addition or removal of shapes", "Movement between corners or sections", "Alternating colour or shading", "Two patterns operating at the same time"] },
    { heading: "Eliminate before selecting", paragraphs: ["If the full rule is unclear, remove answers that break an obvious feature. This reduces cognitive load and often reveals the remaining transformation."] },
    { heading: "Timed practice", paragraphs: ["Review diagrams at high clarity and practise on a screen similar to the expected testing environment. Record which pattern types repeatedly slow you down."] },
  ] },
  { slug: "pma-interview-questions-preparation", title: "PMA Interview Questions and Preparation", description: "Prepare natural answers about motivation, education, family, awareness, strengths and responsibility.", category: "PMA Initial", readTime: "8 min", updated: "August 21, 2026", sections: [
    { heading: "Know your own record", paragraphs: ["Interview preparation begins with your application and biodata. Be ready to discuss education, interests, responsibilities, achievements, setbacks and the reasons behind important choices."] },
    { heading: "Motivation questions", paragraphs: ["Explain why military service fits your values and abilities without repeating slogans. Connect motivation to real examples of discipline, responsibility, teamwork or service."] },
    { heading: "Awareness questions", paragraphs: ["Follow major national and international developments. Practise giving a short factual summary followed by a balanced personal view. Admit respectfully when you do not know something."] },
    { heading: "Delivery", paragraphs: ["Listen to the complete question, pause briefly and answer directly. A concise truthful response is stronger than a long memorised speech."] },
  ] },
  { slug: "issb-five-day-schedule", title: "ISSB Five-Day Schedule: What Candidates Should Expect", description: "A clear overview of reporting, psychological assessment, GTO tasks, interviews and conference stages.", category: "ISSB", readTime: "9 min", updated: "August 21, 2026", sections: [
    { heading: "Reporting and administration", paragraphs: ["Candidates report with the documents and clothing listed in the call letter. Initial administration may include identity checks, chest numbers, accommodation and briefing. Your call letter is the final source for timing and required items."] },
    { heading: "Psychological assessment", paragraphs: ["Written activities can include word association, sentence completion, picture stories and self-description. Time pressure is part of the observation, so practise natural concise responses rather than model answers."] },
    { heading: "GTO and interview work", paragraphs: ["Group discussion, planning and outdoor tasks observe practical cooperation, initiative and influence. Interviews explore personal history, motivation, awareness and consistency with written information."] },
    { heading: "Conference and departure", paragraphs: ["The board combines observations across domains. A re-interview or additional task may occur when clarification is needed. Do not interpret one difficult activity as the final result."] },
  ] },
  { slug: "issb-word-association-test-guide", title: "ISSB Word Association Test Guide", description: "How to practise fast, natural and constructive WAT responses without memorising artificial sentences.", category: "ISSB", readTime: "7 min", updated: "August 21, 2026", sections: [
    { heading: "What WAT reveals", paragraphs: ["The Word Association Test places a candidate under brief time pressure and samples habitual thinking. It is not a vocabulary competition and there is rarely one perfect sentence."] },
    { heading: "Write a complete natural thought", paragraphs: ["Respond to the idea triggered by the word. Keep the sentence short enough to finish. Constructive does not mean unrealistically positive; it means showing workable thought and action."] },
    { heading: "Avoid common traps", paragraphs: ["Do not force every word into leadership, patriotism or success. Avoid memorised templates, moral lectures and sentences that contradict your actual behaviour."] },
    { heading: "Practice method", paragraphs: ["Use short timed sets, then review patterns across many answers. Look for excessive fear, blame, passivity or repetition. Improve your daily thinking and habits rather than merely editing sentences."] },
  ] },
  { slug: "issb-sentence-completion-test", title: "ISSB Sentence Completion Test Preparation", description: "A method for completing English and Urdu sentence stems naturally, quickly and consistently.", category: "ISSB", readTime: "7 min", updated: "August 21, 2026", sections: [
    { heading: "Purpose of sentence completion", paragraphs: ["Incomplete stems invite spontaneous responses about relationships, goals, stress, authority and self-image. Assessors consider broad patterns, not a single isolated line."] },
    { heading: "Complete the idea directly", paragraphs: ["Read the stem once and finish it with the first clear, truthful idea. Keep grammar simple. Do not waste limited time searching for impressive wording."] },
    { heading: "Consistency matters", paragraphs: ["Your sentence completions, stories, self-description and interview should reflect the same real person. Artificial perfection becomes difficult to maintain across many activities."] },
    { heading: "Prepare in both languages", paragraphs: ["Practise concise written expression in English and Urdu. Review handwriting speed and readability as well as the content of your responses."] },
  ] },
  { slug: "issb-group-planning-exercise", title: "ISSB Group Planning Exercise: A Practical Method", description: "Learn to identify problems, resources, priorities, timings and a workable group plan.", category: "ISSB", readTime: "8 min", updated: "August 21, 2026", sections: [
    { heading: "Understand the situation first", paragraphs: ["Read for people, locations, distances, available transport, deadlines and restrictions. Mark facts before proposing solutions."] },
    { heading: "Prioritise problems", paragraphs: ["Consider danger to life, urgency, wider impact and dependencies. Some actions can happen simultaneously if resources and people are divided logically."] },
    { heading: "Test feasibility", paragraphs: ["Estimate travel and action time. Name who will do what, using which resource and by what route. A dramatic plan that ignores distance or time is not practical."] },
    { heading: "Contribute to the group", paragraphs: ["Present your strongest point clearly, listen to corrections and help combine useful ideas. Leadership is visible in progress toward a workable group decision, not in speaking continuously."] },
  ] },
  { slug: "issb-interview-preparation", title: "ISSB Interview Preparation: Questions, Awareness and Confidence", description: "Prepare for personal, educational, motivational and current-affairs questions with truthful examples.", category: "ISSB", readTime: "9 min", updated: "August 21, 2026", sections: [
    { heading: "Your biodata drives the interview", paragraphs: ["Expect follow-up questions about family, education, responsibilities, friends, interests, strengths, weaknesses and important events. Review dates and facts without inventing ideal answers."] },
    { heading: "Use evidence", paragraphs: ["When describing a quality, provide a real example. Explain the situation, your action and what changed. This is more convincing than simply calling yourself confident or responsible."] },
    { heading: "Build current awareness", paragraphs: ["Read reliable news and practise short summaries of major issues. Separate facts from opinion. A balanced view can acknowledge trade-offs and uncertainty."] },
    { heading: "Confidence without performance", paragraphs: ["Sit attentively, listen and answer the question asked. If you do not know, say so calmly. Confidence is compatible with honesty and reflection."] },
  ] },
];

export function getBlogPost(slug: string) { return blogPosts.find(post => post.slug === slug); }
