import type { ContentBlock } from "@/lib/blog-cms";
export type RichNode={type:string;attrs?:Record<string,unknown>;content?:RichNode[];text?:string;marks?:{type:string;attrs?:Record<string,unknown>}[]};
const allowed=new Set(["doc","paragraph","heading","text","bulletList","orderedList","listItem","blockquote","horizontalRule","hardBreak","image","youtube","table","tableRow","tableHeader","tableCell"]);
const marks=new Set(["bold","italic","underline","strike","highlight","link","code"]);
export function sanitizeRichNode(value:unknown,depth=0):RichNode|null{if(depth>20||!value||typeof value!=="object")return null;const x=value as RichNode;if(!allowed.has(x.type))return null;const node:RichNode={type:x.type};if(typeof x.text==="string")node.text=x.text.slice(0,50000);if(Array.isArray(x.marks))node.marks=x.marks.filter(m=>m&&marks.has(m.type)).map(m=>({type:m.type,attrs:m.type==="link"?{href:safeUrl(String(m.attrs?.href||"")),target:"_blank",rel:"noopener noreferrer"}:m.attrs}));if(x.attrs){const a=x.attrs;node.attrs={};if(x.type==="heading")node.attrs.level=Math.min(4,Math.max(2,Number(a.level)||2));if(x.type==="image"){node.attrs.src=safeUrl(String(a.src||""));node.attrs.alt=String(a.alt||"").slice(0,180);node.attrs.title=String(a.title||"").slice(0,180);}if(x.type==="youtube")node.attrs.src=safeUrl(String(a.src||""));if(["tableCell","tableHeader"].includes(x.type)){node.attrs.colspan=Math.min(10,Math.max(1,Number(a.colspan)||1));node.attrs.rowspan=Math.min(20,Math.max(1,Number(a.rowspan)||1));}if(x.type==="paragraph")node.attrs.textAlign=["left","center","right"].includes(String(a.textAlign))?a.textAlign:null;}if(Array.isArray(x.content))node.content=x.content.map(c=>sanitizeRichNode(c,depth+1)).filter(Boolean) as RichNode[];return node;}
function safeUrl(url:string){return /^(https?:\/\/|\/)/i.test(url)?url.slice(0,1000):"";}
const text=(value:string):RichNode=>({type:"text",text:value});
export function blocksToRichDoc(blocks:ContentBlock[]):RichNode{return{type:"doc",content:blocks.flatMap(b=>{if(b.type==="heading")return[{type:"heading",attrs:{level:2},content:[text(b.text)]}];if(b.type==="list")return[{type:"bulletList",content:(b.items||[]).map(x=>({type:"listItem",content:[{type:"paragraph",content:[text(x)]}]}))}];if(b.type==="quote")return[{type:"blockquote",content:[{type:"paragraph",content:[text(b.text)]}]}];if(b.type==="cta"||b.type==="callout")return[{type:"blockquote",content:[{type:"paragraph",content:[text(b.text)]}]}];return[{type:"paragraph",content:b.text?[text(b.text)]:[]}];})};}
export function richText(node?:RichNode):string{return node?[node.text||"",...(node.content||[]).map(richText)].join(" ").replace(/\s+/g," ").trim():"";}
export function richHeadings(node?:RichNode):{id:string;text:string}[]{const out:{id:string;text:string}[]=[];function walk(n?:RichNode){if(!n)return;if(n.type==="heading"){const t=richText(n);if(t)out.push({id:`section-${out.length+1}`,text:t});}(n.content||[]).forEach(walk);}walk(node);return out;}
