import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Ban, Coins, ShoppingBag, UserCheck, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { isAdminEmail } from "@/lib/admin";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { blockReferral } from "../actions";

export const dynamic = "force-dynamic";

export default async function AdminReferralsPage() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const { data: profile } = await supabase.from("users").select("role").eq("id", user.id).maybeSingle(); if (profile?.role !== "admin" && !isAdminEmail(user.email)) redirect("/dashboard"); const { data } = await createAdminClient().from("referrals").select("id,status,created_at,referrer:users!referrals_referrer_id_fkey(name,email),referred:users!referrals_referred_user_id_fkey(name,email)").order("created_at", { ascending: false }).limit(500); const rows = data || []; const qualified = rows.filter(row => row.status === "qualified" || row.status === "purchased").length; const purchased = rows.filter(row => row.status === "purchased").length;
  return <main className="mx-auto max-w-7xl px-5 py-10"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-bold text-primary"><ArrowLeft className="h-4 w-4" />Admin dashboard</Link><div className="mt-6"><p className="text-sm font-bold uppercase tracking-wider text-primary">Growth operations</p><h1 className="mt-2 text-3xl font-black">Referral programme</h1><p className="mt-2 text-slate-500">Review attribution, qualification and purchase conversion. Block suspicious pending rewards.</p></div><section className="mt-7 grid gap-4 sm:grid-cols-4"><Metric icon={Users} label="Invites" value={rows.length} /><Metric icon={UserCheck} label="Qualified" value={qualified} /><Metric icon={ShoppingBag} label="Purchased" value={purchased} /><Metric icon={Coins} label="Credits issued" value={qualified * 50 + purchased * 150} /></section><section className="mt-9 space-y-3">{rows.map(row => { const referrer = row.referrer as unknown as { name?: string; email?: string } | null; const referred = row.referred as unknown as { name?: string; email?: string } | null; return <Card key={row.id}><CardContent className="grid gap-4 pt-6 sm:grid-cols-[1fr_1fr_auto] sm:items-center"><div><p className="text-xs font-bold uppercase text-slate-400">Referrer</p><p className="mt-1 font-bold">{referrer?.name || referrer?.email || "Unknown"}</p></div><div><p className="text-xs font-bold uppercase text-slate-400">Invited candidate</p><p className="mt-1 font-bold">{referred?.name || referred?.email || "Unknown"}</p><p className="mt-1 text-xs text-slate-500">{new Date(row.created_at).toLocaleDateString()}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black uppercase">{row.status}</span>{["pending", "qualified"].includes(row.status) && <form action={blockReferral.bind(null, row.id)}><Button size="sm" variant="outline"><Ban className="mr-2 h-4 w-4 text-red-600" />Block</Button></form>}</div></CardContent></Card>})}</section></main>; }
function Metric({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: number }) { return <Card><CardContent className="flex items-center gap-3 pt-6"><Icon className="h-5 w-5 text-primary" /><div><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="text-2xl font-black">{value}</p></div></CardContent></Card>; }
