import Link from "next/link";
import { ArrowRight, Brain, Clock3, Dumbbell, ListChecks, MessageSquare, Stethoscope, Target } from "lucide-react";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
const roadmap=[["01","Academic MCQs","50 questions · 25–30 min · 50% pass",Target],["02","Verbal Intelligence","60–84 questions · 30 min · 50% pass",Brain],["03","Non-Verbal Intelligence","60–70 questions · 30 min · 50% pass",ListChecks],["04","Medical Examination","Eyesight, hearing, blood pressure and BMI",Stethoscope],["05","Physical Tests","Running, push-ups, sit-ups and chin-ups",Dumbbell],["06","Interview","Confidence, communication and general knowledge",MessageSquare]]as const;
const modules=[{test:"/initial/mcqs/academic",title:"Academic MCQs",description:"English, Maths, General Knowledge, Islamic Studies, Current Affairs, Pak Studies and General Science.",icon:Target},{test:"/initial/mcqs/verbal",title:"Verbal Intelligence",description:"Analogies, alphabet and number series, coding-decoding and logic puzzles.",icon:Brain},{test:"/initial/mcqs/non-verbal",title:"Non-Verbal Intelligence",description:"Pattern recognition, sequences and image-based diagram questions.",icon:ListChecks}];
export default async function Page(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");return <main className="mx-auto max-w-7xl px-5 py-10"><section className="rounded-[2rem] bg-slate-950 px-6 py-12 text-white shadow-xl sm:px-10"><p className="text-sm font-bold uppercase tracking-[.22em] text-emerald-300">PMA Initial Course</p><h1 className="mt-3 text-4xl font-black sm:text-5xl">Roadmap to PMA Selection</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Build your foundation with lessons and timed tests, then prepare your health, fitness and communication.</p><Button asChild className="mt-6"><Link href="/initial/lessons">Open Initial lessons <ArrowRight className="ml-2 h-4 w-4"/></Link></Button></section><section className="mt-12"><p className="text-sm font-bold uppercase tracking-wider text-primary">Your route</p><h2 className="mt-2 text-2xl font-black">Six stages, one focused direction</h2><div className="mt-7 grid gap-4 md:grid-cols-3 xl:grid-cols-6">{roadmap.map(([number,title,detail,Icon])=><div className="rounded-2xl border bg-white p-5 shadow-sm" key={number}><div className="grid h-11 w-11 place-items-center rounded-full bg-primary text-sm font-black text-white">{number}</div><div className="mt-5 flex items-start justify-between gap-3"><h3 className="text-sm font-black">{title}</h3><Icon className="h-5 w-5 shrink-0 text-primary"/></div><p className="mt-3 text-xs leading-5 text-slate-500">{detail}</p></div>)}</div></section><section className="mt-14"><p className="text-sm font-bold uppercase tracking-wider text-primary">Core tests</p><h2 className="mt-2 text-3xl font-black">Learn, practise, then test</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{modules.map(({test,title,description,icon:Icon})=><Card key={test}><CardContent className="flex h-full flex-col pt-6"><div className="grid h-12 w-12 place-items-center rounded-xl bg-green-50 text-primary"><Icon/></div><h3 className="mt-5 text-2xl font-black">{title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-slate-600">{description}</p><Button asChild className="mt-6"><Link href={test}>Start test <ArrowRight className="ml-2 h-4 w-4"/></Link></Button></CardContent></Card>)}</div></section><div className="mt-10 flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-950"><Clock3 className="h-5 w-5 shrink-0"/><p><strong>Test rule:</strong> Timed tests submit automatically when time expires.</p></div></main>}
