import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, BookOpen, ClipboardCheck, Crown, Map, WalletCards } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { isAdminEmail } from "@/lib/admin";

const areas=[
  {title:"Initial Preparation",text:"Lessons, academic MCQs, verbal and non-verbal intelligence preparation.",href:"/initial",icon:ClipboardCheck},
  {title:"ISSB Preparation",text:"Psychology, visual GTO lessons and interview guidance.",href:"/issb",icon:Map},
  {title:"Preparation Guides",text:"Read practical public articles and preparation strategies.",href:"/blog",icon:BookOpen},
];

export default async function Dashboard(){const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)redirect("/login");if(isAdminEmail(user.email))redirect("/admin");const[{data:profile},{data:passes}]=await Promise.all([s.from("users").select("name,credit_balance,premium_status").eq("id",user.id).maybeSingle(),s.from("user_entitlements").select("scope,expires_at").eq("user_id",user.id).gt("expires_at",new Date().toISOString())]);const scopes=new Set((passes||[]).map(x=>x.scope)),access=profile?.premium_status?"Complete pass":scopes.has("initial")&&scopes.has("issb")?"Initial + ISSB":scopes.has("initial")?"Initial pass":scopes.has("issb")?"ISSB pass":"Starter access";return <main className="mx-auto max-w-6xl px-5 py-10"><header><p className="text-sm font-black uppercase tracking-widest text-emerald-700">Candidate dashboard</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Welcome, {profile?.name?.split(" ")[0]||"Candidate"}</h1><p className="mt-2 text-slate-500">Choose where you want to continue.</p></header><section className="mt-7 flex flex-wrap items-center gap-3 rounded-2xl border bg-white p-4 sm:p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Crown className="h-5 w-5"/></span><div><p className="text-xs font-bold text-slate-400">Your access</p><p className="font-black">{access}</p></div></div><div className="ml-auto flex items-center gap-2 text-sm font-bold text-slate-600"><WalletCards className="h-4 w-4 text-amber-600"/>{profile?.credit_balance??100} credits</div></section><section className="mt-8 grid gap-5 md:grid-cols-3">{areas.map(({title,text,href,icon:Icon})=><Link href={href} key={href} className="group rounded-2xl border bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-emerald-300 hover:shadow-lg"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-5 w-5"/></span><h2 className="mt-5 text-xl font-black">{title}</h2><p className="mt-2 min-h-20 text-sm leading-6 text-slate-500">{text}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-black text-emerald-700">Open <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></span></Link>)}</section><div className="mt-8 text-center"><Link href="/upgrade" className="text-sm font-bold text-slate-500 hover:text-emerald-700">Manage access and credits</Link></div></main>}
