import Link from "next/link";
import { ArrowLeft, BookOpen, CheckCircle2, Play, Target } from "lucide-react";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const content = {
  academic: { title: "Academic MCQs", test: "/initial/mcqs/academic", concept: "Academic questions reward clear basics and careful reading. Revise English vocabulary, arithmetic, percentages, general knowledge, Islamic Studies, Pak Studies, current affairs and science.", example: "For percentages, convert the question into a simple fraction or decimal before calculating. For a 50% question, divide by 2.", notes: "/initial/notes" },
  verbal: { title: "Verbal Intelligence", test: "/initial/mcqs/verbal", concept: "Verbal intelligence tests relationships between words and numbers. Check analogies first, then differences, ratios, alternate series and coding rules.", example: "In 3, 7, 11, 15, the difference is +4, so the next number is 19. Always state the rule before choosing.", notes: "/initial/notes" },
  "non-verbal": { title: "Non-Verbal Intelligence", test: "/initial/mcqs/non-verbal", concept: "Non-verbal questions ask you to see movement, rotation, growth, repetition and position. Compare one visual feature at a time rather than guessing from the whole image.", example: "For a rotating shape, track its direction after each step. For a sequence, check whether the number of sides, dots or lines changes consistently.", notes: "/initial/notes" },
} as const;

export default async function TutorialPage({ params }: { params: Promise<{ module: string }> }) {
  const { module } = await params; const lesson = content[module as keyof typeof content]; if (!lesson) notFound();
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  return <main className="mx-auto max-w-4xl px-5 py-10"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-primary" href="/initial"><ArrowLeft className="h-4 w-4" />PMA roadmap</Link><div className="mt-7"><p className="text-sm font-bold uppercase tracking-wider text-primary">Tutorial</p><h1 className="mt-2 text-4xl font-black">{lesson.title}</h1><p className="mt-3 text-lg leading-8 text-slate-600">Learn the approach, practise with the timer, and review notes before your next attempt.</p></div><div className="mt-8 grid grid-cols-3 gap-2 rounded-xl border bg-white p-2 text-center text-sm font-bold"><a className="rounded-lg bg-primary px-3 py-3 text-white" href="#concept">Concept</a><a className="rounded-lg px-3 py-3 text-slate-600 hover:bg-slate-50" href="#practice">Practice</a><a className="rounded-lg px-3 py-3 text-slate-600 hover:bg-slate-50" href="#notes">Notes</a></div><section id="concept" className="mt-6"><Card><CardContent className="pt-6"><Target className="h-7 w-7 text-primary" /><h2 className="mt-4 text-2xl font-black">Understand the concept</h2><p className="mt-3 leading-8 text-slate-600">{lesson.concept}</p><div className="mt-5 rounded-xl bg-green-50 p-4 text-sm leading-6 text-green-950"><strong>Worked idea:</strong> {lesson.example}</div></CardContent></Card></section><section id="practice" className="mt-5"><Card><CardContent className="flex flex-wrap items-center justify-between gap-4 pt-6"><div><Play className="h-7 w-7 text-primary" /><h2 className="mt-4 text-2xl font-black">Practise under pressure</h2><p className="mt-2 text-sm leading-6 text-slate-600">The timer is visible, cannot be paused, and submits automatically when it reaches zero.</p></div><Button asChild><Link href={lesson.test}>Start timed test</Link></Button></CardContent></Card></section><section id="notes" className="mt-5"><Card><CardContent className="flex flex-wrap items-center justify-between gap-4 pt-6"><div><BookOpen className="h-7 w-7 text-primary" /><h2 className="mt-4 text-2xl font-black">Review notes</h2><p className="mt-2 text-sm leading-6 text-slate-600">Read the secure study PDFs uploaded by your administrator before repeating the test.</p></div><Button asChild variant="outline"><Link href={lesson.notes}>Open notes <CheckCircle2 className="ml-2 h-4 w-4" /></Link></Button></CardContent></Card></section></main>;
}
